version: 2
formats: []

build:
  image: latest

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  version: 3.8
  install:
    - requirements: req-rtd.txt
    - method: pip
      path: .
      extra_requirements:
        - docs
