version: 2
formats: []

build:
  image: latest

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false
  builder: html

python:
  version: 3.9
  install:
   - requirements: docs/requirements.txt
   - requirements: req-rtd.txt
