name: Publish to PyPi

on:
  push:
    branches:
      - "release/*"
      - "main"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests setuptools wheel twine
    - name: Get Latest Pre-Release
      working-directory: .github/workflows/
      run: |
        final=$(python get_revision.py)
        echo "WAVELINK_VERSION=$final" >> $GITHUB_ENV
    - name: Find and Replace
      uses: jacobtomlinson/gha-find-replace@master
      with:
        find: "{{__VERSION__}}"
        replace: ${{ env.WAVELINK_VERSION }}
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
